### ISSUE TITLE
Don't black out while downloading a thumbnail

### ISSUE THREAD

**Issue by VarunAgw** [nnarhinen/flowplayer-thumbnails#11]
When downloading a thumbnail, it blackens the area. My suggestion is to keep showing the last thumbnail displayed while it is downloading.

Example code:

```
            seconds = time_format(seconds + 1);
            var url = template.replace('{time}', seconds - seconds % 4);

            var image = new Image();
            image.src = url;
            image.onload = function () {
                common.css(timelineTooltip, {
                    width: (height / ratio) + 'px',
                    height: height + 'px',
                    'background-image': "url('" + url + "')",
                    'background-repeat': 'no-repeat',
                    'background-size': 'cover',
                    'background-position': 'center',
                    'border': '1px solid #333',
                    'text-shadow': '1px 1px #000'
                });
            };
```

**Comment by phloxic** [comment]
@VarunAgw - thank you.
I'm not entirely convinced though:
- technically: if consistent immediate display matters leave `preload` at `true`, and do not use a splash setup. That should rather take care of it, shouldn't it?
- UI: arguably the 'wrong' image sort of defeats the purpose as it's misleading, whereas a black square with the correct time is not.

What do you think?

**Comment by VarunAgw** [comment]
@blacktrash 

I've seen many sites which shows last thumbnail instead of black screen. And I don't think it is misleading. Anyone can guess the thumbnail is loading if it is not changed yet.

Anyway, It was just a minor suggestion. I have manually modified my local copy. If you feel it is not a good idea, feel free to close the issue :)

**Comment by phloxic** [comment]
I'll play around with your suggestion in the next couple of days.
Obviously also depends on the size of the images, and how optimized they are.

**Comment by phloxic** [comment]
@VarunAgw - I think this goes nicely in conjunction with `preload: false`. There's a mild irritation with images changing while one actually hovers on one position, but arguably this outweighs the frustration of a black square.
With `preload: true` doing the same thing for all images sequentially, the updating becomes rather hectic with long videos over a slow connection: you can observe more hectic updates which border on annoying.

If you like you can try http://flowplayer.blacktrash.org/fp6/flowplayer.thumbnails.js - it has an additional option `lazyload` defaulting to `true` which implements your suggestion. I am considering the following:
1. as the test script, both `preload` and `lazyload` enabled
2. change the default of `preload` to `false`
3. no additional option: no "lazyload" with `preload: true` (which should then default to `false`), "lazyload" otherwise

Opinions?

**Comment by VarunAgw** [comment]
> change the default of preload to false
> 3. no additional option: no "lazyload" with preload: true

So you are suggesting enabling or disabling preload by default?

I don't know if other peoples use `preload: true`, but I personally don't like the idea of sending 1000's of thumbnail request. Chances are user is not going to seek at all.

One more suggestion if you are interested is to put `var image = new Image();` outside of the event. So a new `image.src` cancels the last request. If I hover to "09:10", "09:20",... it will only show thumbnail of currently hover position rather than showing all of them for few ms while other load. 

Alternatively if you want to cache those thumbnails instead of canceling request, we can compare mouse position with `src` at onload event. But I think it will add bit of complexity

**Comment by phloxic** [comment]
`preload` _is_ the current default (personaly I do not like it either ;-))
I don't understand what you mean by 'outside the event' - which event? For what I called `lazyload` (your suggestion) it must be inside the mousemove event, mustn't it?
Personally my preference would be `preload: false, lazyload: true` with my test script above.

**Comment by VarunAgw** [comment]
> Personally my preference would be preload: false, lazyload: true with my test script above.

Same here :+1: 

> I don't understand what you mean by 'outside the event' - which event?

I mean reusing the same `image` variable by changing its src instead of creating new every time.

**Comment by phloxic** [comment]
@VarunAgw - good idea.
- I will introduce this new `lazyload` option, and it will be enabled by default
- regarding `preload`: the default behaviour will be that preloading is disabled

**Comment by phloxic** [comment]
@VarunAgw - thank you for the new default behaviour ;-)
Closing.

**Comment by VarunAgw** [comment]
Just checked, works perfectly. Thanks :)
