### ISSUE TITLE
support sprites / contact sheets

### ISSUE THREAD

**Issue by bbbo** [nnarhinen/flowplayer-thumbnails#12]
ie a plugin version which loads one image and references the required sprite / image according to  timeline position

**Comment by heychrisek** [comment]
Hi there. Thanks for a great product! (both Flowplayer and this plugin).

I'm customizing the flowplayer-thumbnails plugin to accommodate a single JPG using sprites for a project, so I could submit a PR once everything's in place.

What are your thoughts on the API design? I'd propose a new `sprite` property, which would include metadata about the shape of the sprite grid.

For example, this configuration would work with [this contact sheet](https://i9.ytimg.com/sb/dQw4w9WgXcQ/storyboard3_L1/M0.jpg?sigh=rs%24AOn4CLCWHVZ8pzEp0Lqo295b9Ae8YLab0Q) (taken from Youtube), but is flexible to handle other grid shapes.

```
thumbnails: {
  template: 'thumbnails/contact-sheet.jpg', // single file, not necessarily a template
  sprite: {
    thumbnailWidth: 80,     // width of thumbnail within overall image
    thumbnailHeight: 45,    // height of thumbnail within overall image
    thumbnailsPerRow: 10    // so plugin knows when to look at next line of thumbnails
  }
}
```

Do you have any thoughts or anything else I should know?

**Comment by phloxic** [comment]
@heychrisek - thank you very much, the [PR](https://github.com/flowplayer/flowplayer-thumbnails/pull/14) is looking pretty good.
I can take care of stuff like backwards-compatibility with old IEs etc (we don't transpile this small plugin).
Give me a couple of days, and I believe we can integrate this.

**Comment by phloxic** [comment]
@heychrisek - thanks again for your contribution. It's now in. Sorry for delay, I'm on sick leave.

**Comment by heychrisek** [comment]
Thanks @blacktrash . No problem at all. Welcome back from leave!
