### ISSUE TITLE
make plugin official?

### ISSUE THREAD

**Issue by phloxic** [nnarhinen/flowplayer-thumbnails#6]
I'm all for it.

Then it could have a place at https://flowplayer.org/docs/plugins.html (until again some wild restructuring sets in), and at http://demos.flowplayer.org/api/thumbnails.html for instance - I think it deserves its own page there, not together with http://demos.flowplayer.org/scripting/timeline-thumbnail.html because imho it's better suited for real production purposes (of course referencing each other).

just my 2¢

btw, personally I think the quality-selector(s) should also be at releases.flowplayer.org - unless this is a problem with Drive gallery etc.

**Comment by nnarhinen** [comment]
Ok, I will transfer this plugin under flowplayer org. Did you just volunteer to do the demos etc? ;)

**Comment by phloxic** [comment]
Yes, I did, stupid me ;-)
